### ISSUE TITLE
[Feature] Group <-> Role sync

### ISSUE THREAD

**Issue by underscore11code** [Hexaoxide/CarbonCord#4]
### Proposed Feature Description:
Syncing of Luckperms Groups and Discord Roles for Linked (#3) users.

### Proposed Feature Functionality:
```yml
group-role-sync:
  my-first-sync:
    discord-role-id: "123456789"
    luckperms-group-name: "iron"
    # Which side determines if a user has a group or not. Possible options something along the lines of
    # DISCORD, ROLE, CARBON, MINECRAFT, LUCKPERMS, GROUP
    authoritative-side: LUCKPERMS
  another-sync:
    # ...
```
